document.addEventListener('DOMContentLoaded',()=>{
 const header=document.getElementById('siteHeader');const menuButton=document.getElementById('menuButton');const nav=document.getElementById('navigation');const heroVideo=document.getElementById('heroVideo');
 const onScroll=()=>header&&header.classList.toggle('scrolled',window.scrollY>28);onScroll();window.addEventListener('scroll',onScroll,{passive:true});
 if(menuButton&&nav){menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('active');menuButton.setAttribute('aria-expanded',open?'true':'false');document.body.classList.toggle('menu-open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('active');document.body.classList.remove('menu-open');menuButton.setAttribute('aria-expanded','false')}));}
 if(heroVideo){heroVideo.muted=true;const p=heroVideo.play();if(p)p.catch(()=>{});}
 const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -35px 0px'});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
 const heroStage=document.getElementById('heroStage'),heroPhone=document.getElementById('heroPhone');if(heroStage&&heroPhone){heroStage.addEventListener('mousemove',e=>{if(innerWidth<900)return;const r=heroStage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;heroPhone.style.transform=`translateY(-6px) rotateY(${x*14-12}deg) rotateX(${y*-9+3}deg) translate(${x*7}px,${y*6}px)`});heroStage.addEventListener('mouseleave',()=>heroPhone.style.transform='translateY(-6px) rotateY(-12deg) rotateX(3deg)');}
 const UIs={
  0:`<p class="ui-kicker">GUEST ORDER</p><h4>Table 08</h4><div class="ui-card">New order<strong>3 items received</strong></div><div class="ui-list"><div><span>Chicken Burger ×2</span><b>LKR 3,700</b></div><div><span>Iced Latte ×1</span><b>LKR 950</b></div><div><span>Total</span><b>LKR 4,650</b></div></div>`,
  1:`<p class="ui-kicker">LIVE POS</p><h4>Orders</h4><div class="ui-card">Table 06<strong>3 items · New</strong></div><div class="ui-card">Room 304<strong>2 items · Preparing</strong></div><div class="ui-card">Table 12<strong>5 items · Ready</strong></div>`,
  2:`<p class="ui-kicker">KITCHEN / KOT</p><h4>KOT #184</h4><div class="ui-status"><i></i>2 × Chicken Burger</div><div class="ui-status"><i></i>1 × French Fries</div><div class="ui-status"><i></i>1 × Iced Coffee</div><div class="ui-card">Status<strong>Preparing</strong></div>`,
  3:`<p class="ui-kicker">MANAGEMENT</p><h4>Operations</h4><div class="ui-card">Overview<strong>Live activity</strong></div><div class="ui-chart"><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="ui-list"><div><span>Menu</span><b>Active</b></div><div><span>Kitchen</span><b>Connected</b></div></div>`
 };
 const themes={0:{name:'GUEST ORDERING',glow:'#c56b42',bg:'#f0e9dc'},1:{name:'POS & ORDER FLOW',glow:'#d4aa63',bg:'#eee5d5'},2:{name:'KITCHEN / KOT',glow:'#7f8d73',bg:'#e8eadf'},3:{name:'MANAGEMENT',glow:'#633743',bg:'#eadfe3'}};
 const deviceContent=document.getElementById('deviceContent'),label=document.getElementById('productLabel'),sticky=document.getElementById('stickyProduct'),glow=document.querySelector('.product-glow'),dots=[...document.querySelectorAll('.story-dot')],scenes=[...document.querySelectorAll('.story-scene')];
 const setStep=i=>{if(deviceContent)deviceContent.innerHTML=UIs[i];if(label)label.textContent=themes[i].name;if(glow)glow.style.background=themes[i].glow;if(deviceContent)deviceContent.style.background=themes[i].bg;dots.forEach((d,n)=>d.classList.toggle('active',n===i));if(sticky)sticky.style.setProperty('--accent',themes[i].glow)};setStep(0);
 const sceneObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.45)setStep(Number(e.target.dataset.step))}),{threshold:[.45,.6]});scenes.forEach(s=>sceneObserver.observe(s));dots.forEach((d,i)=>d.addEventListener('click',()=>{scenes[i].scrollIntoView({behavior:'smooth',block:'center'});setStep(i)}));
 const productDevice=document.getElementById('productDevice');if(sticky&&productDevice){sticky.addEventListener('mousemove',e=>{if(innerWidth<900)return;const r=sticky.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;productDevice.style.transform=`perspective(1100px) rotateY(${x*12}deg) rotateX(${y*-8}deg)`});sticky.addEventListener('mouseleave',()=>productDevice.style.transform='');}
});
